# Generated by Django 5.2.12 on 2026-03-05 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Shabbat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('is_open', models.BooleanField(default=True)),
                ('yavne_open', models.BooleanField(default=False)),
                ('ayyanot_open', models.BooleanField(default=False)),
                ('has_delivery', models.BooleanField(default=False)),
                ('employees', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shabbats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_walk_in', models.BooleanField(default=False)),
                ('location', models.CharField(choices=[('yavne', 'Yavne'), ('ayyanot', 'Ayyanot')], max_length=10)),
                ('order_type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=10)),
                ('delivery_time', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('done', 'Done')], default='waiting', max_length=10)),
                ('payment_type', models.CharField(choices=[('bit', 'Bit'), ('paybox', 'Paybox'), ('cash', 'Cash'), ('credit', 'Credit'), ('none', 'None')], default='none', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.customer')),
                ('shabbat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.shabbat')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('yavne', 'Yavne'), ('ayyanot', 'Ayyanot')], max_length=10)),
                ('jachnun', models.IntegerField(default=0)),
                ('jachnun_butter', models.IntegerField(default=0)),
                ('kubane', models.IntegerField(default=0)),
                ('burekas_cheese', models.IntegerField(default=0)),
                ('burekas_potato', models.IntegerField(default=0)),
                ('burekas_spinach', models.IntegerField(default=0)),
                ('malabi', models.IntegerField(default=0)),
                ('orange_juice', models.IntegerField(default=0)),
                ('shabbat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='api.shabbat')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
